# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-29 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, '\u7533\u8bf7'), (1, '\u901a\u8fc7'), (2, '\u62d2\u7edd')], null=True, verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
    ]
